CREATE TABLE IF NOT EXISTS ai_invocation /* AI middleware storage */ (
    id INTEGER PRIMARY KEY /* SQLite row ID */,
    task_key TEXT NOT NULL /* Registered AI task */,
    task_version INTEGER NOT NULL CHECK (task_version > 0) /* Code-owned task contract version */,
    prompt_key TEXT NOT NULL /* Registered task prompt identity */,
    prompt_version INTEGER NOT NULL CHECK (prompt_version > 0) /* Resolved immutable prompt version */,
    model_id INTEGER NOT NULL CHECK (model_id > 0) /* Configured model logical ID */,
    model_name TEXT NOT NULL /* Provider model identifier */,
    run_id TEXT NOT NULL DEFAULT '' /* Optional scheduler run correlation */,
    attempt INTEGER NOT NULL DEFAULT 1 CHECK (attempt > 0) /* Single-call attempt ordinal */,
    status TEXT NOT NULL CHECK (status IN ('STARTED', 'SUCCEEDED', 'REJECTED', 'ERROR')) /* STARTED, SUCCEEDED, REJECTED or ERROR */,
    result_code TEXT NOT NULL DEFAULT '' /* Safe task outcome code */,
    error_code TEXT NOT NULL DEFAULT '' /* Safe runtime error code, never exception text */,
    latency_ms INTEGER NOT NULL DEFAULT 0 CHECK (latency_ms >= 0) /* Elapsed attempt duration in milliseconds */,
    input_tokens INTEGER NOT NULL DEFAULT -1 CHECK (input_tokens >= -1) /* Provider prompt tokens; -1 means UNKNOWN */,
    output_tokens INTEGER NOT NULL DEFAULT -1 CHECK (output_tokens >= -1) /* Provider completion tokens; -1 means UNKNOWN */,
    total_tokens INTEGER NOT NULL DEFAULT -1 CHECK (total_tokens >= -1) /* Reported or derived total tokens; -1 means UNKNOWN */,
    cached_tokens INTEGER NOT NULL DEFAULT -1 CHECK (cached_tokens >= -1) /* Provider cached prompt tokens; -1 means UNKNOWN */,
    cost_usd TEXT NOT NULL DEFAULT '' /* SDK estimated USD cost as decimal text; empty means UNKNOWN */,
    request_json TEXT NOT NULL /* Local audit messages and response_format only, excluding credentials and connection settings */,
    response_text TEXT NOT NULL DEFAULT '' /* Local provider message content; not exposed by HTTP */,
    response_truncated INTEGER NOT NULL DEFAULT 0 CHECK (response_truncated IN (0, 1)) /* 1 if capture exceeded 256 KiB */,
    created_time TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f000Z', 'now')) /* UTC ISO-8601 timestamp with six fractional digits */,
    updated_time TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f000Z', 'now')) /* UTC ISO-8601 timestamp with six fractional digits */
);
